name: ci

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: ls
        run: ls -lart lib

      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v1
        with:
          registry-url: 'https://npm.pkg.github.com'

      - name: Publish
        run: |
          git config user.name "biolibtech"
          git config user.email "biolibtech"
          yarn version --new-version 0.0.$GITHUB_RUN_NUMBER
          yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

